# ***Aufgabe 2*** 
**101 NumPy** 

If you have not done so already, really work through the first 25 examples of the 101 NumPy exercises

Laura Pichlmeier - 70454892

## **1. Import numpy as np and see the version**

In [ ]:
import numpy as np
print(np.__version__)

1.21.6


## **2. How to create a 1D array?**

In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## **3. How to create a boolean array?**

In [ ]:
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## **4. How to extract items that satisfy a given condition from 1D array?**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[arr % 2 == 1])

[1 3 5 7 9]


## **5. How to replace items that satisfy a condition with another value in numpy array?**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## **6. How to replace items that satisfy a condition without affecting the original array?**

In [ ]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(' ')
print(out)



[0 1 2 3 4 5 6 7 8 9]
 
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## **7. How to reshape an array?**

In [ ]:
np.arange(10)

arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## **8. How to stack two arrays vertically?**

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## **9. How to stack two arrays horizontally?**

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## **10. How to generate custom sequences in numpy without hardcoding?**

In [ ]:
a = np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## **11. How to get the common items between two python numpy arrays?**

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


## **12. How to remove from one array those items that exist in another?**

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print(np.setdiff1d(a,b))

[1 2 3 4]


## **13. How to get the positions where elements of two arrays match?**

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a == b))

(array([1, 3, 5, 7]),)


## **14. How to extract all numbers between a given range from a numpy array?**

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where(np.logical_and(a>=5, a<=10))
print(a[index])

[ 6  9 10]


In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

## **15. How to make a python function that handles scalars to work on numpy arrays?**

In [ ]:
def maxx(x, y):
    
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a, b))


[6. 7. 9. 8. 9. 7. 5.]


## **16. How to swap two columns in a 2d numpy array?**

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(' ')

print(arr[:, [1, 0, 2]])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[1 0 2]
 [4 3 5]
 [7 6 8]]


## **17. How to swap two rows in a 2d numpy array?**

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(' ')

print(arr[[1, 0, 2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[3 4 5]
 [0 1 2]
 [6 7 8]]


## **18. How to reverse the rows of a 2D array?**

In [ ]:
arr = np.arange(9).reshape(3,3)

print(arr[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## **19. How to reverse the columns of a 2D array?**

In [ ]:
arr = np.arange(9).reshape(3,3)

print(arr[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## **20. How to create a 2D array containing random floats between 5 and 10?**

In [ ]:
arr = np.arange(9).reshape(3,3)

rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.27759009 7.7907785  6.17542563]
 [6.33084307 9.88823147 7.15750754]
 [5.36043436 6.77688781 6.13246156]
 [5.30535301 6.37088028 9.50609284]
 [6.51978171 8.35638559 7.34580652]]


In [ ]:
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[8.59111424 7.38322161 9.03461434]
 [6.28906017 5.25179345 5.29941528]
 [5.33567648 7.80316233 6.88865874]
 [5.67901978 6.1524517  7.30170533]
 [9.62956659 9.42857678 7.93663444]]


## **21. How to print only 3 decimal places in python numpy array?**

In [ ]:
rand_arr = np.random.random((5,3))

np.set_printoptions(precision=3)
print(rand_arr[:4])

[[0.355 0.667 0.685]
 [0.076 0.076 0.297]
 [0.329 0.027 0.89 ]
 [0.412 0.006 0.767]]


## **22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?**

In [ ]:
np.set_printoptions(suppress=False)

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
print(' ')

np.set_printoptions(suppress=True, precision=6)  # precision is optional
print(rand_arr)

[[5.434049e-04 2.783694e-04 4.245176e-04]
 [8.447761e-04 4.718856e-06 1.215691e-04]
 [6.707491e-04 8.258528e-04 1.367066e-04]]
 
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


## **23. How to limit the number of items printed in output of numpy array?**

In [ ]:
np.set_printoptions(threshold=6)

a = np.arange(15)
print(a)


[ 0  1  2 ... 12 13 14]


## **24. How to print the full numpy array without truncating**

In [ ]:
np.set_printoptions(threshold=6)

a = np.arange(15)
print(a)

import sys
np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## **25. How to import a dataset with numbers and texts keeping the text intact in python numpy?**

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


# **I have read and done the first 25 exersises!!!**